version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#    restart: always
    volumes:
      - elastic_movies_data:/var/lib/elasticsearch/data
    networks:
      - movies_network

  movies-redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis_data:/var/lib/redis/data
#    restart: always
    networks:
      - movies_network

  movies-api:
    build:
      context: src/
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - movies-redis
#    restart: always
    networks:
      - movies_network

  nginx-async-api:
    image: nginx:1.19.2
    depends_on:
      - movies-api
      - movies-redis
      - elasticsearch
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    restart: always
    networks:
      - movies_network

volumes:
  elastic_movies_data:
  redis_data:

networks:
  movies_network:
    external: true
    name: movies_network